### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by pastukhov** [geek/pebble-socket-example#1]
I'm getting [

``` javascript
PHONE] pebble-app.js:?: JavaScript Error:
ReferenceError: WebSocket is not defined
    at Object.loader (app.js:3:14)
    at Object.loader.require (loader.js:44:10)
    at require (loader.js:41:48)
```

**Comment by geek** [comment]
Interesting... WebSocket should be on the `window` object.  Please check that you have a `window` and see what else is available.

**Comment by pastukhov** [comment]
My fault, it's working only on real pebble but not on online emulator.
